[build]
        base = "."
        publish = "public/"

[functions]
        node_bundler = "esbuild"
        
[[redirects]]
  from = "/v1/*"
  to = "https://generativelanguage.googleapis.com/v1beta/openai/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

